version: "3.8"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - MAIN_ADMIN_IDS=${MAIN_ADMIN_IDS}
      - PORT=5000
    env_file:
      - .env
    volumes:
      - ./dist:/app/dist
    restart: unless-stopped
