[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  publish = "dist"

[[redirects]]
  from = "/api/orders"
  to = "/.netlify/functions/orders"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/orders"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200